version: '3.8'
services:
  ms-customer:
    build: .
    ports:
      - "9004:9004"
    depends_on:
      - customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/customer
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_FLYWAY_URL: jdbc:postgresql://customer-db:5432/customer
      SPRING_FLYWAY_USER: user
      SPRING_FLYWAY_PASSWORD: password
      SPRING_PROFILES_ACTIVE: testData

  customer-db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
    ports:
      - "5432:5432"
    volumes:
      - customer-db-data:/var/lib/postgresql/data

volumes:
  customer-db-data:
